export const Data = [
  {
    id: 1,
    category:"Emulsion",
    image: "/Images/1.png",
    title: "data.title",
    CharacteristicT: "data.1.CharacteristicT",
    Characteristic: "data.1.Characteristic",
    MethodsT: "data.1.Methods of usageT",
    Methods: "data.1.Methods of usage",
    UsageT: "data.1.UsageT",
    Usage: "data.1.Usage",
    InstructionsT: "data.1.InstructionsT",
    Instructions: "data.1.Instructions",
    ConsumptionT: "data.1.ConsumptionT",
    Consumption: "data.1.Consumption",
    ContentT: "data.1.ContentT",
    Content: "data.1.Content",
    BestT: "data.1.Best beforeT",
    Best: "data.1.Best before",
    StorageT: "data.1.Storage conditionsT",
    Storage: "data.1.Storage conditions",
    ManufacturerT: "data.1.ManufacturerT",
    Manufacturer: "data.1.Manufacturer",
  },
  {
    id: 2,
    category:"Emulsion",
    image: "/Images/2.png",
    title: "data.title",
    CharacteristicT: "data.1.CharacteristicT",
    Characteristic: "data.1.Characteristic",
    MethodsT: "data.1.Methods of usageT",
    Methods: "data.1.Methods of usage",
    UsageT: "data.1.UsageT",
    Usage: "data.1.Usage",
    InstructionsT: "data.1.InstructionsT",
    Instructions: "data.1.Instructions",
    ConsumptionT: "data.1.ConsumptionT",
    Consumption: "data.1.Consumption",
    ContentT: "data.1.ContentT",
    Content: "data.1.Content",
    BestT: "data.1.Best beforeT",
    Best: "data.1.Best before",
    StorageT: "data.1.Storage conditionsT",
    Storage: "data.1.Storage conditions",
    ManufacturerT: "data.1.ManufacturerT",
    Manufacturer: "data.1.Manufacturer",
  },
  {
    id: 3,
    category:"Emulsion",
    image: "/Images/3.png",
    title: "data.title",
    CharacteristicT: "data.1.CharacteristicT",
    Characteristic: "data.1.Characteristic",
    MethodsT: "data.1.Methods of usageT",
    Methods: "data.1.Methods of usage",
    UsageT: "data.1.UsageT",
    Usage: "data.1.Usage",
    InstructionsT: "data.1.InstructionsT",
    Instructions: "data.1.Instructions",
    ConsumptionT: "data.1.ConsumptionT",
    Consumption: "data.1.Consumption",
    ContentT: "data.1.ContentT",
    Content: "data.1.Content",
    BestT: "data.1.Best beforeT",
    Best: "data.1.Best before",
    StorageT: "data.1.Storage conditionsT",
    Storage: "data.1.Storage conditions",
    ManufacturerT: "data.1.ManufacturerT",
    Manufacturer: "data.1.Manufacturer",
  },
  {
    id: 4,
    category:"Emulsion",
    image: "/Images/4.png",
    title: "data.title4",
    DescriptionT: "data.4.DescriptionT",
    Description: "data.4.Description",
    CharacteristicT: "data.4.CharacteristicT",
    Characteristic: "data.4.Characteristic",
    ApplyT: "data.4.ApplyT",
    Apply: "data.4.Apply",
    MethodsT: "data.4.Methods of usageT",
    Methods: "data.4.Methods of usage",
    UsageT: "data.4.UsageT",
    Usage: "data.4.Usage",
    InstructionsT: "data.4.InstructionsT",
    Instructions: "data.4.Instructions",
    ConsumptionT: "data.4.ConsumptionT",
    Consumption: "data.4.Consumption",
    ContentT: "data.4.ContentT",
    Content: "data.4.Content",
    SolventT: "data.4.SolventT",
    Solvent: "data.4.Solvent",
    FlammabilityT: "data.4.FlammabilityT",
    Flammability: "data.4.Flammability",
    ApplicationT: "data.4.Application temperatureT",
    Application: "data.4.Application temperature",
    BestT: "data.4.Best beforeT",
    Best: "data.4.Best before",
    StorageT: "data.4.Storage conditionsT",
    Storage: "data.4.Storage conditions",
    CompleteT: "data.4.CompleteT",
    Complete: "data.4.Complete",
  },
  {
    id: 5,
    category:"Dur plaster",
    image: "/Images/5.png",
    title: "data.title5",
    DescriptionT: "data.5.DescriptionT",
    Description: "data.5.Description",
    InstructionsT: "data.5.InstructionsT",
    Instructions: "data.5.Instructions",
    ContentT: "data.5.ContentT",
    Content: "data.5.Content",
  },
  {
    id: 6,
    category:"Lak",
    image: "/Images/6.png",
    title: "data.title6",
    DescriptionT: "data.5.DescriptionT",
    Description: "data.5.Description",
    InstructionsT: "data.5.InstructionsT",
    Instructions: "data.5.Instructions",
    ContentT: "data.5.ContentT",
    Content: "data.5.Content",
  },
  {
    id: 7,
    category:"Primer",
    image: "/Images/7.png",
    title: "data.title7",
    DescriptionT: "data.5.DescriptionT",
    Description: "data.5.Description",
    InstructionsT: "data.5.InstructionsT",
    Instructions: "data.5.Instructions",
    ContentT: "data.5.ContentT",
    Content: "data.5.Content",
  },
  {
    id: 8,
    category:"Travertine",
    image: "/Images/8.png",
    title: "data.title8",
    DescriptionT: "data.8.DescriptionT",
    Description: "data.8.Description",
    CharacteristicT: "data.8.CharacteristicT",
    Characteristic:"data.8.Characteristic",
    ApplyT: "data.8.ApplyT",
    Apply: "data.8.Apply",
    MethodsT: "data.8.Methods of usageT",
    Methods: "data.8.Methods of usage",
    UsageT: "data.8.UsageT",
    Usage: "data.8.Usage",
  InstructionsT: "data.8.InstructionsT",
    Instructions: "data.8.Instructions",
    ConsumptionT: "data.8.ConsumptionT",
    Consumption: "data.8.Consumption",
    ContentT: "data.8.ContentT",
    Content: "data.8.Content",
    SolventT: "data.8.SolventT",
    Solvent: "data.8.Solvent",
    FlammabilityT: "data.8.FlammabilityT",
    Flammability: "data.8.Flammability",
    ApplicationT: "data.8.Application temperatureT",
    Application: "data.8.Application temperature",
    BestT: "data.8.Best beforeT",
    Best: "data.8.Best before",
    StorageT: "data.8.Storage conditionsT",
    Storage: "data.8.Storage conditions",
  },
  {
    id: 9,
    category:"Primer Astar",
    image: "/Images/9.png",
    title: "data.title9",
    CharacteristicT: "data.1.CharacteristicT",
    Characteristic: "data.1.Characteristic",
    MethodsT: "data.1.Methods of usageT",
    Methods: "data.1.Methods of usage",
    UsageT: "data.1.UsageT",
    Usage: "data.1.Usage",
    InstructionsT: "data.1.InstructionsT",
    Instructions: "data.1.Instructions",
    ConsumptionT: "data.1.ConsumptionT",
    Consumption: "data.1.Consumption",
    ContentT: "data.1.ContentT",
    Content: "data.1.Content",
    BestT: "data.1.Best beforeT",
    Best: "data.1.Best before",
    StorageT: "data.1.Storage conditionsT",
    Storage: "data.1.Storage conditions",
    ManufacturerT: "data.1.ManufacturerT",
    Manufacturer: "data.1.Manufacturer",
  },
  {
    id: 10,
    category:"Mineral plaster",
    image: "/Images/10.png",
    title: "data.title10",
    DescriptionT: "data.4.DescriptionT",
    Description: "data.4.Description",
    CharacteristicT: "data.4.CharacteristicT",
    Characteristic: "data.4.Characteristic",
    ApplyT: "data.4.ApplyT",
    Apply: "data.4.Apply",
    MethodsT: "data.4.Methods of usageT",
    Methods: "data.4.Methods of usage",
    UsageT: "data.4.UsageT",
    Usage: "data.4.Usage",
    InstructionsT: "data.4.InstructionsT",
    Instructions: "data.4.Instructions",
    ConsumptionT: "data.4.ConsumptionT",
    Consumption: "data.4.Consumption",
    ContentT: "data.4.ContentT",
    Content: "data.4.Content",
    SolventT: "data.4.SolventT",
    Solvent: "data.4.Solvent",
    FlammabilityT: "data.4.FlammabilityT",
    Flammability: "data.4.Flammability",
    ApplicationT: "data.4.Application temperatureT",
    Application: "data.4.Application temperature",
    BestT: "data.4.Best beforeT",
    Best: "data.4.Best before",
    StorageT: "data.4.Storage conditionsT",
    Storage: "data.4.Storage conditions",
    CompleteT: "data.4.CompleteT",
    Complete: "data.4.Complete",
  },
];
